name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: raschidjfr/ionic-blank:ionic8-angular19-cypress14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build -- -c production

    - name: Run tests
      working-directory: /app
      run: |
          mkdir cypress
          cp -r /cypress/* ./cypress
          cp /cypress.config.ts .
          cp -r /src/app/home/* ./src/app/home
          npm i dist/ionic-header-parallax-$(cd dist/ionic-header-parallax && npm pkg get version).tgz
          ng serve --host 0.0.0.0 --port 4200 &
          (wait-on http://0.0.0.0:4200 --timeout 30000 --interval 1000 && cypress run --headless) \
          || { echo 'Angular server failed to start'; exit 1; }
